### ISSUE TITLE
Ability to disable in development

### ISSUE THREAD

**Issue by duncanmcclean** [thoughtco/statamic-stop-forum-spam#1]
Thanks for this great addon, going into production with it soon 🚀

It would be great if it was possible to disable the spam check in development environments. 

I use the "Fake Filler" chrome extension for testing. However, all the emails it generates are considered spam emails. It would be great if it was possible to disable the check so I can use fake details while testing locally.

**Comment by ryanmitchell** [comment]
Maybe something like this? https://github.com/thoughtco/statamic-stop-forum-spam/pull/2

**Comment by duncanmcclean** [comment]
Yeah, that'd be perfect. Thanks!
